// export const arrayData = [
//   { payment_1: "payment_1",
//   { payment_2: "payment_2",
//   { payment_3: "payment_3",
//   { payment_4: "payment_4",
//   { bs_1: "bs_1",
//   { bs_2: "bs_2",
//   { bs_3: "bs_3",
//   { f1: "f1",
//   { f2: "f2",
//   { f3: "f3",
//   { ht1: "ht1",
//   { ht2: "ht2",
//   { ht3: "ht3",
//   { discount: "discount",
//   { category1: "category1",
//   { category2: "category2",
//   { category3: "category3",
//   { category4: "category4",
//   { category5: "category5",
//   { product1: "product1",
//   { product2: "product2",
//   { product3: "product3",
//   { product4: "product4",
//   { product5: "product5",
//   { product6: "product6",
//   { product7: "product7",
//   { product8: "product8",
// ];

export const items = [
  {
    title: "Furry hooded parka",
    price: " 59.0",
    cloudinaryPublicId: "watches/rssqmtcc9uktfysg7off",
    associativeImgs: [
      "watches/rssqmtcc9uktfysg7off",
      "watches/rssqmtcc9uktfysg7off",
      "watches/uylshku94fzkncpiwxqf",
      "watches/zc4l52kkq5ckh2fplsbv",
      "watches/t7uovvup4njs4oi1zvij",
    ],
  },
  {
    title: "Flowy striped skirt",
    price: " 49.0",
    cloudinaryPublicId: "watches/rssqmtcc9uktfysg7off",
    associativeImgs: [
      "watches/rssqmtcc9uktfysg7off",
      "watches/rssqmtcc9uktfysg7off",
      "watches/uylshku94fzkncpiwxqf",
      "watches/zc4l52kkq5ckh2fplsbv",
      "watches/t7uovvup4njs4oi1zvij",
    ],
  },
  {
    title: "Croc-effect bag",
    price: " 59.0",
    cloudinaryPublicId: "watches/uylshku94fzkncpiwxqf",
    associativeImgs: [
      "watches/rssqmtcc9uktfysg7off",
      "watches/rssqmtcc9uktfysg7off",
      "watches/uylshku94fzkncpiwxqf",
      "watches/zc4l52kkq5ckh2fplsbv",
      "watches/t7uovvup4njs4oi1zvij",
    ],
  },
  {
    title: "Dark wash Xavi jeans",
    price: " 59.0",
    cloudinaryPublicId: "watches/zc4l52kkq5ckh2fplsbv",
    associativeImgs: [
      "watches/rssqmtcc9uktfysg7off",
      "watches/rssqmtcc9uktfysg7off",
      "watches/uylshku94fzkncpiwxqf",
      "watches/zc4l52kkq5ckh2fplsbv",
      "watches/t7uovvup4njs4oi1zvij",
    ],
  },
  {
    title: "Furry hooded parka",
    price: " 59.0",
    cloudinaryPublicId: "watches/t7uovvup4njs4oi1zvij",
    associativeImgs: [
      "watches/rssqmtcc9uktfysg7off",
      "watches/rssqmtcc9uktfysg7off",
      "watches/uylshku94fzkncpiwxqf",
      "watches/zc4l52kkq5ckh2fplsbv",
      "watches/t7uovvup4njs4oi1zvij",
    ],
  },
  {
    title: "Flowy striped skirt",
    price: " 49.0",
    cloudinaryPublicId: "watches/et9yukvhryufnlcl6tm9",
    associativeImgs: [
      "watches/rssqmtcc9uktfysg7off",
      "watches/rssqmtcc9uktfysg7off",
      "watches/uylshku94fzkncpiwxqf",
      "watches/zc4l52kkq5ckh2fplsbv",
      "watches/t7uovvup4njs4oi1zvij",
    ],
  },
  {
    title: "Croc-effect bag",
    price: " 59.0",
    cloudinaryPublicId: "watches/lprcew5glxcroojady0x",
    associativeImgs: [
      "watches/rssqmtcc9uktfysg7off",
      "watches/rssqmtcc9uktfysg7off",
      "watches/uylshku94fzkncpiwxqf",
      "watches/zc4l52kkq5ckh2fplsbv",
      "watches/t7uovvup4njs4oi1zvij",
    ],
  },
  {
    title: "Furry hooded parka",
    price: " 59.0",
    cloudinaryPublicId: "watches/rssqmtcc9uktfysg7off",
    associativeImgs: [
      "watches/rssqmtcc9uktfysg7off",
      "watches/rssqmtcc9uktfysg7off",
      "watches/uylshku94fzkncpiwxqf",
      "watches/zc4l52kkq5ckh2fplsbv",
      "watches/t7uovvup4njs4oi1zvij",
    ],
  },
  {
    title: "Flowy striped skirt",
    price: " 49.0",
    cloudinaryPublicId: "watches/rssqmtcc9uktfysg7off",
    associativeImgs: [
      "watches/rssqmtcc9uktfysg7off",
      "watches/rssqmtcc9uktfysg7off",
      "watches/uylshku94fzkncpiwxqf",
      "watches/zc4l52kkq5ckh2fplsbv",
      "watches/t7uovvup4njs4oi1zvij",
    ],
  },
  {
    title: "Croc-effect bag",
    price: " 59.0",
    cloudinaryPublicId: "watches/uylshku94fzkncpiwxqf",
    associativeImgs: [
      "watches/rssqmtcc9uktfysg7off",
      "watches/rssqmtcc9uktfysg7off",
      "watches/uylshku94fzkncpiwxqf",
      "watches/zc4l52kkq5ckh2fplsbv",
      "watches/t7uovvup4njs4oi1zvij",
    ],
  },
  {
    title: "Dark wash Xavi jeans",
    price: " 59.0",
    cloudinaryPublicId: "watches/zc4l52kkq5ckh2fplsbv",
    associativeImgs: [
      "watches/rssqmtcc9uktfysg7off",
      "watches/rssqmtcc9uktfysg7off",
      "watches/uylshku94fzkncpiwxqf",
      "watches/zc4l52kkq5ckh2fplsbv",
      "watches/t7uovvup4njs4oi1zvij",
    ],
  },
  {
    title: "Furry hooded parka",
    price: " 59.0",
    cloudinaryPublicId: "watches/t7uovvup4njs4oi1zvij",
    associativeImgs: [
      "watches/rssqmtcc9uktfysg7off",
      "watches/rssqmtcc9uktfysg7off",
      "watches/uylshku94fzkncpiwxqf",
      "watches/zc4l52kkq5ckh2fplsbv",
      "watches/t7uovvup4njs4oi1zvij",
    ],
  },
  {
    title: "Flowy striped skirt",
    price: " 49.0",
    cloudinaryPublicId: "watches/et9yukvhryufnlcl6tm9",
    associativeImgs: [
      "watches/rssqmtcc9uktfysg7off",
      "watches/rssqmtcc9uktfysg7off",
      "watches/uylshku94fzkncpiwxqf",
      "watches/zc4l52kkq5ckh2fplsbv",
      "watches/t7uovvup4njs4oi1zvij",
    ],
  },
  {
    title: "Croc-effect bag",
    price: " 59.0",
    cloudinaryPublicId: "watches/lprcew5glxcroojady0x",
    associativeImgs: [
      "watches/rssqmtcc9uktfysg7off",
      "watches/rssqmtcc9uktfysg7off",
      "watches/uylshku94fzkncpiwxqf",
      "watches/zc4l52kkq5ckh2fplsbv",
      "watches/t7uovvup4njs4oi1zvij",
    ],
  },
  {
    title: "Dark wash Xavi jeans",
    price: " 59.0",
    cloudinaryPublicId: "watches/lprcew5glxcroojady0x",
    associativeImgs: [
      "watches/rssqmtcc9uktfysg7off",
      "watches/rssqmtcc9uktfysg7off",
      "watches/uylshku94fzkncpiwxqf",
      "watches/zc4l52kkq5ckh2fplsbv",
      "watches/t7uovvup4njs4oi1zvij",
    ],
  },
  {
    title: "Furry hooded parka",
    price: " 59.0",
    cloudinaryPublicId: "watches/u5za2m8pzfqztzwx0a8y",
    associativeImgs: [
      "watches/rssqmtcc9uktfysg7off",
      "watches/rssqmtcc9uktfysg7off",
      "watches/uylshku94fzkncpiwxqf",
      "watches/zc4l52kkq5ckh2fplsbv",
      "watches/t7uovvup4njs4oi1zvij",
    ],
  },
  {
    title: "Flowy striped skirt",
    price: " 49.0",
    cloudinaryPublicId: "watches/u5za2m8pzfqztzwx0a8y",
    associativeImgs: [
      "watches/rssqmtcc9uktfysg7off",
      "watches/rssqmtcc9uktfysg7off",
      "watches/uylshku94fzkncpiwxqf",
      "watches/zc4l52kkq5ckh2fplsbv",
      "watches/t7uovvup4njs4oi1zvij",
    ],
  },
  {
    title: "Croc-effect bag",
    price: " 59.0",
    cloudinaryPublicId: "watches/u5za2m8pzfqztzwx0a8y",
    associativeImgs: [
      "watches/rssqmtcc9uktfysg7off",
      "watches/rssqmtcc9uktfysg7off",
      "watches/uylshku94fzkncpiwxqf",
      "watches/zc4l52kkq5ckh2fplsbv",
      "watches/t7uovvup4njs4oi1zvij",
    ],
  },
  {
    title: "Dark wash Xavi jeans",
    price: " 59.0",
    cloudinaryPublicId: "watches/u5za2m8pzfqztzwx0a8y",
    associativeImgs: [
      "watches/rssqmtcc9uktfysg7off",
      "watches/rssqmtcc9uktfysg7off",
      "watches/uylshku94fzkncpiwxqf",
      "watches/zc4l52kkq5ckh2fplsbv",
      "watches/t7uovvup4njs4oi1zvij",
    ],
  },
  // Add more items here
];
